Live updates
justcalamari/codeu_project_2017 pull request #2
Opened 2017-04-18 23:18 UTC by justcalamari

Implemented automatic updates.

2017-04-18 23:18 UTC, justcalamari commented
@sambrv @EthanSchoen Ready for review.

2017-05-10 06:30 UTC, narendergupta requested changes

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/ClientContext.java
> +
Extra newline.

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/ClientContext.java
Extra newline.

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/ClientContext.java
> +    private static final int SERVER_REFRESH_MS = 5000;  // 5 seconds
Some files have 2-space tab while others have 4-space tabs. Please make them consistent.

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/ClientContext.java
> +
Lots of extra newlines. Please fix.

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/ClientContext.java
> +                    //conversation.updateAllConversations(false);
Add a comment for why the line is commented out, or remove it altogether.

2017-05-10 06:30 UTC, narendergupta commented on src/codeu/chat/client/simplegui/ChatSimpleGui.java
> +        @Override
Inconsistent 2-4 spaced tabs.

2017-05-30 22:16 UTC, EthanSchoen approved these changes

2017-06-02 22:11 UTC, merged